name = "hnjobs-api"
main = "src/index.ts"
compatibility_date = "2024-01-01" # Adjust as needed
compatibility_flags = ["nodejs_compat"]

[vars]
# Add environment variables here if needed

[[d1_databases]]
binding = "DB"
database_name = "hnjobs-db"
database_id = "4b9236d5-bae7-4daf-baa8-ad50a90382f9"